# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Chatbots
tagline:          'Synthèse de veille technologique'
description:      'cacaDans le cadre de mes études à l''École Centrale de Lyon, j''ai effectué une veille technologique sur les thème des Chatbots. Ce site a pour but de restituer l''enseignement que j''ai tiré de ce projet.<br><br>Made by <a href="https://twitter.com/Augustin_ECL" target="_blank">@Augustin_ECL</a>.'
url:              adurivault.github.io
baseurl:          /hyde/

author:
  name:           'Augustin Durivault'
  url:            https://twitter.com/Augustin_ECL

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
    - jekyll-gist
